export const ALAT_LIST_REQUEST = 'ALAT_LIST_REQUEST';
export const ALAT_LIST_SUCCESS = 'ALAT_LIST_SUCCESS';
export const ALAT_LIST_FAIL = 'ALAT_LIST_FAIL';

export const ALAT_DETAILS_REQUEST = 'ALAT_DETAILS_REQUEST';
export const ALAT_DETAILS_SUCCESS = 'ALAT_DETAILS_SUCCESS';
export const ALAT_DETAILS_FAIL = 'ALAT_DETAILS_FAIL';