export const ALAT_LIST_REQUEST = 'ALAT_LIST_REQUEST';
export const ALAT_LIST_SUCCESS = 'ALAT_LIST_SUCCESS';
export const ALAT_LIST_FAIL = 'ALAT_LIST_FAIL';

export const ALAT_DETAILS_REQUEST = 'ALAT_DETAILS_REQUEST';
export const ALAT_DETAILS_SUCCESS = 'ALAT_DETAILS_SUCCESS';
export const ALAT_DETAILS_FAIL = 'ALAT_DETAILS_FAIL';

export const ALAT_SAVE_REQUEST = 'ALAT_SAVE_REQUEST';
export const ALAT_SAVE_SUCCESS = 'ALAT_SAVE_SUCCESS';
export const ALAT_SAVE_FAIL = 'ALAT_SAVE_FAIL';

export const ALAT_DELETE_REQUEST = 'ALAT_DELETE_REQUEST';
export const ALAT_DELETE_SUCCESS = 'ALAT_DELETE_SUCCESS';
export const ALAT_DELETE_FAIL = 'ALAT_DELETE_FAIL';
export const ALAT_DELETE_RESET = 'ALAT_DELETE_RESET';

export const ALAT_CREATE_REQUEST = 'ALAT_CREATE_REQUEST';
export const ALAT_CREATE_SUCCESS = 'ALAT_CREATE_SUCCESS';
export const ALAT_CREATE_FAIL = 'ALAT_CREATE_FAIL';
export const ALAT_CREATE_RESET = 'ALAT_CREATE_RESET';